# Generated by Django 5.0.2 on 2024-04-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_portal', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
