# Generated by Django 5.0.2 on 2024-05-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_portal', '0014_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
