# Generated by Django 5.0.2 on 2024-05-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_portal', '0016_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='question',
            new_name='qun',
        ),
    ]
