# Generated by Django 5.0.2 on 2024-05-02 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_portal', '0017_rename_question_faq_qun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='qun',
            new_name='ask',
        ),
    ]
