# Generated by Django 5.0.2 on 2024-05-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_portal', '0019_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='ask',
            new_name='question',
        ),
    ]
